# Generated by Django 5.2.5 on 2025-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
